import type { CategoryId } from "./types";
import type { DB } from "./types";
import { ASSETS } from "./assets";

const day = (offset: number, hour = 10): string =>
  new Date(Date.UTC(2026, 7, 24 + offset, hour, 30)).toISOString();

export const CATEGORIES: {
  id: CategoryId;
  label: string;
  short: string;
  image: string;
  blurb: string;
}[] = [
  { id: "koti", label: "Koti ja asuminen", short: "Koti", image: ASSETS.catKoti, blurb: "Remontit, siivous, sähkötyöt ja LVI" },
  { id: "digi", label: "Digitaaliset palvelut", short: "Digi", image: ASSETS.catDigi, blurb: "Verkkosivut, brändit, markkinointi" },
  { id: "hyvinvointi", label: "Hyvinvointi", short: "Hyvinvointi", image: ASSETS.catHyvinvointi, blurb: "Hieronta, jooga, valmennus" },
  { id: "tapahtumat", label: "Tapahtumat", short: "Tapahtumat", image: ASSETS.catTapahtumat, blurb: "Juhlat, catering, kuvaus, ohjelma" },
  { id: "kuljetus", label: "Kuljetus", short: "Kuljetus", image: ASSETS.catKuljetus, blurb: "Muutot, kuljetukset, kantoapu" },
  { id: "opetus", label: "Opetus", short: "Opetus", image: ASSETS.catOpetus, blurb: "Tunnit, kurssit ja valmennukset" },
  { id: "muut", label: "Muut", short: "Muut", image: ASSETS.catMuut, blurb: "Pihatyöt ja kaikki muu osaaminen" },
];

export const categoryById = (id: CategoryId) => CATEGORIES.find((c) => c.id === id);

export const DELIVERY_LABEL = {
  paikan_paalla: "Paikan päällä",
  etana: "Etätyö",
} as const;

export const PRICING_LABEL = {
  tunti: "Tuntihinta",
  paketti: "Kiinteä hinta",
  tarjous: "Tarjouspyyntö",
} as const;

export const PAYMENT_LABEL = {
  alusta: "Maksu alustan kautta",
  ulkopuolella: "Maksu alustan ulkopuolella",
} as const;

export const ORDER_STATUS_LABEL: Record<string, string> = {
  sovitaan: "Sovitaan yksityiskohdista",
  maksettu: "Maksettu",
  valmis: "Valmis",
  peruttu: "Peruttu",
};

export const LANGUAGES = ["suomi", "ruotsi", "englanti", "venäjä", "viro", "espanja", "saksa"];

export function buildSeed(): DB {
  return {
    users: [
      { id: "u-mikko", name: "Mikko Virtanen", email: "mikko@etsipro.fi", password: "demo1234", role: "tarjoaja", providerId: "p-mikko" },
      { id: "u-liisa", name: "Liisa Niemi", email: "liisa@etsipro.fi", password: "demo1234", role: "asiakas" },
      { id: "u-emilia", name: "Emilia Korhonen", email: "emilia@studioemilia.fi", password: "demo1234", role: "tarjoaja", providerId: "p-emilia" },
      { id: "u-suvi", name: "Suvi Nieminen", email: "suvi@hyvinvointisuvi.fi", password: "demo1234", role: "tarjoaja", providerId: "p-suvi" },
      { id: "u-juhani", name: "Juhani Lahti", email: "juhani@lahtimuutot.fi", password: "demo1234", role: "tarjoaja", providerId: "p-juhani" },
      { id: "u-anna", name: "Anna Laakso", email: "anna@musiikkikoulu.fi", password: "demo1234", role: "tarjoaja", providerId: "p-anna" },
      { id: "u-lumo", name: "Lumo Events", email: "info@lumoevents.fi", password: "demo1234", role: "tarjoaja", providerId: "p-lumo" },
      { id: "u-olli", name: "Olli Mäkelä", email: "olli@vihreapeukalo.fi", password: "demo1234", role: "tarjoaja", providerId: "p-olli" },
      { id: "u-antti", name: "Antti Virtala", email: "antti@example.fi", password: "demo1234", role: "asiakas" },
    ],
    providers: [
      {
        id: "p-mikko",
        name: "Sähköasennus Virtanen",
        tagline: "Sähkötyöt ammattitaidolla – jo 15 vuoden ajalta.",
        bio: "Olen sähköalan ammattilainen Helsingistä. Teen kodin ja yritysten sähkötyöt aina sovitusti ja siististi: valaistuksen asennukset, pistorasiat, sähkökeskukset sekä pienemmät remonttikohteet.\n\nJokainen työ alkaa ilmaisella kartoituskäynnillä, jonka jälkeen saat selkeän tarjouksen – ei yllätyksiä. Työskentelen S2-pätevyydellä ja kaikki työt tehdään voimassa olevien säädösten mukaan.",
        avatarUrl: ASSETS.portraitMikko,
        bannerUrl: ASSETS.catKoti,
        city: "Helsinki",
        languages: ["suomi", "englanti"],
        experienceYears: 15,
        categories: ["koti"],
        rating: 4.8,
        reviewCount: 95,
        joinedYear: 2021,
        social: { instagram: "sahkoasennusv", website: "https://example.com" },
        certifications: ["S2-sähköpätevyys (TUKES)", "Ensiapukortti EA1"],
        faq: [
          { q: "Teetkö myös pieniä töitä?", a: "Kyllä! Ei ole liian pientä työtä – valaisimen asennuksesta kokonaisiin remontteihin." },
          { q: "Miten saan tarjouksen?", a: "Lähetä varauspyyntö tai viesti. Käyn paikalla kartoittamassa ilmaiseksi ja lähetän tarjouksen vuorokauden sisällä." },
          { q: "Onko työlläsi takuu?", a: "Kaikilla töillä on 24 kuukauden asennustakuu." },
        ],
        portfolioImages: [ASSETS.svcBathroom, ASSETS.catKoti],
      },
      {
        id: "p-emilia",
        name: "Studio Emilia",
        tagline: "Verkkosivut ja brändit, jotka myyvät puolestasi.",
        bio: "Suunnittelen verkkosivuja ja brändi-ilmeitä yrityksille, jotka haluavat erottua edukseen. Yhdistän selkeän viestinnän, ajattoman designin ja teknisesti toimivan toteutuksen.\n\nTyöskentelen etänä koko Suomen alueella – tapaamiset hoituvat videolla tai kasvotusten pääkaupunkiseudulla.",
        avatarUrl: ASSETS.portraitEmilia,
        bannerUrl: ASSETS.catDigi,
        city: "Helsinki",
        languages: ["suomi", "englanti", "ruotsi"],
        experienceYears: 8,
        categories: ["digi"],
        rating: 4.9,
        reviewCount: 61,
        joinedYear: 2022,
        social: { instagram: "studioemilia", linkedin: "studio-emilia", website: "https://example.com" },
        certifications: ["Google UX Design -sertifikaatti", "Medianomi (AMK)"],
        faq: [
          { q: "Kauanko verkkosivujen teko kestää?", a: "Tyypillisesti 2–4 viikkoa sisällöistä riippuen. Sovimme aikataulun aina etukäteen." },
          { q: "Sisältyykö ylläpito hintaan?", a: "Ensimmäinen kuukausi ylläpitoa sisältyy hintaan, sen jälkeen edullinen kuukausimaksu." },
        ],
        portfolioImages: [ASSETS.svcWebdesign, ASSETS.catDigi],
      },
      {
        id: "p-suvi",
        name: "Hyvinvointi Suvi",
        tagline: "Keho kuntoon – ammattitaidolla ja lämmöllä.",
        bio: "Olen koulutettu hieroja ja joogaopettaja Tampereelta. Toimin vastaanotollani keskustassa sekä pidän pienryhmien joogakursseja.\n\nTyöni ytimessä on asiakkaan kokonaisvaltainen hyvinvointi: kuuntelen, mitä kehosi kertoo, ja rakennan hoidon tai harjoituksen sen ympärille.",
        avatarUrl: ASSETS.portraitSuvi,
        bannerUrl: ASSETS.catHyvinvointi,
        city: "Tampere",
        languages: ["suomi", "englanti"],
        experienceYears: 10,
        categories: ["hyvinvointi"],
        rating: 4.9,
        reviewCount: 89,
        joinedYear: 2022,
        social: { instagram: "hyvinvointisuvi", facebook: "hyvinvointisuvi" },
        certifications: ["Koulutettu hieroja (KLH)", "Joogaopettaja RYT-200"],
        faq: [
          { q: "Voiko hieronnan maksaa alustan kautta?", a: "Kyllä! Valitse varauksessa maksu alustan kautta ja maksat turvallisesti kortilla." },
          { q: "Onko joogakurssilla tasoryhmiä?", a: "Kurssi sopii erityisesti aloittelijoille, mutta harjoituksista on aina helpompi ja haastavampi variaatio." },
        ],
        portfolioImages: [ASSETS.svcYoga, ASSETS.catHyvinvointi],
      },
      {
        id: "p-juhani",
        name: "Lahti Muutot",
        tagline: "Muutto sujuu – me kannamme.",
        bio: "Toimimme pääkaupunkiseudulla ja teemme muutot sekä yksittäiset kuljetukset sovitusti ja aikataulussa. Kalustosta löytyy pakettiauto ja kuorma-auto sekä kantoapu kaikkiin kerroksiin.\n\nPyydä tarjous: kerro lähtö- ja kohdeosoite sekä tavaramäärä, niin saat kiinteän hinnan vuorokauden sisällä.",
        avatarUrl: ASSETS.portraitJuhani,
        bannerUrl: ASSETS.catKuljetus,
        city: "Helsinki",
        languages: ["suomi", "englanti", "venäjä"],
        experienceYears: 6,
        categories: ["kuljetus"],
        rating: 4.7,
        reviewCount: 141,
        joinedYear: 2021,
        social: { facebook: "lahtimuutot", website: "https://example.com" },
        certifications: ["CE-ajokortti", "Tilaajavastuu.fi-raportti"],
        faq: [
          { q: "Mitä muutto maksaa?", a: "Lähetä varauspyyntö osoitteineen ja tavaramäärineen – saat kiinteän tarjouksen vuorokauden sisällä." },
          { q: "Onko teillä kantoapu?", a: "Kyllä, kantoapu sisältyy kaikkiin muuttoihin kerroksesta riippumatta." },
        ],
        portfolioImages: [ASSETS.catKuljetus],
      },
      {
        id: "p-anna",
        name: "Musiikkikoulu Laakso",
        tagline: "Musiikki kuuluu kaikille – opetusta 20 vuoden kokemuksella.",
        bio: "Opetan pianoa ja musiikin perusteita kaikenikäisille. Tunnit verkossa tai vastaanotollani Oulussa.\n\nPedagogiikkani ytimessä on ilo: opit soittamaan kappaleita, joista pidät, heti ensimmäisistä tunneista lähtien.",
        avatarUrl: ASSETS.portraitAnna,
        bannerUrl: ASSETS.svcPiano,
        city: "Oulu",
        languages: ["suomi", "englanti"],
        experienceYears: 20,
        categories: ["opetus"],
        rating: 5.0,
        reviewCount: 31,
        joinedYear: 2023,
        social: { instagram: "musiikkikoululaakso" },
        certifications: ["Musiikin maisteri, Sibelius-Akatemia"],
        faq: [
          { q: "Tarvitseeko minulla olla oma piano?", a: "Etänä opiskellessa riittää koskettimisto, vastaanotolla on flyygeli." },
          { q: "Minkä ikäisille opetat?", a: "Lapsille 6-vuotiaasta ylöspäin ja aikuisille – koskaan ei ole liian myöhäistä aloittaa." },
        ],
        portfolioImages: [ASSETS.svcPiano, ASSETS.catOpetus],
      },
      {
        id: "p-lumo",
        name: "Lumo Events",
        tagline: "Juhlat, jotka muistetaan.",
        bio: "Suunnittelemme ja toteutamme häiden, yritysjuhlien ja yksityistilaisuuksien somistuksen ja koordinoinnin koko Turun seudulla. Kukista kattauksiin ja valoista ohjelmaan – me hoidamme kokonaisuuden.\n\nPyydä tarjous tapahtumastasi, niin rakennamme juuri teille sopivan paketin.",
        avatarUrl: ASSETS.catTapahtumat,
        bannerUrl: ASSETS.catTapahtumat,
        city: "Turku",
        languages: ["suomi", "ruotsi", "englanti"],
        experienceYears: 5,
        categories: ["tapahtumat"],
        rating: 4.9,
        reviewCount: 14,
        joinedYear: 2023,
        social: { instagram: "lumoevents", website: "https://example.com" },
        certifications: ["Hygieniapassi (tiimi)"],
        faq: [
          { q: "Kuinka ajoissa juhla kannattaa varata?", a: "Suosittelemme varausta 2–3 kuukautta ennen tapahtumaa, sesonkiaikaan aiemmin." },
        ],
        portfolioImages: [ASSETS.catTapahtumat],
        isCompany: true,
      },
      {
        id: "p-olli",
        name: "Vihreä Peukalo",
        tagline: "Pihasi parhaaksi – vuoden ympäri.",
        bio: "Hoidan pihatyöt Espoon ja pääkaupunkiseudun alueella: pensasaitojen leikkaukset, nurmikot, harvennukset ja syys- sekä kevätsiivoukset.\n\nKäyn aina ensin katsomassa kohteen ja annan kiinteän hinnan ennen töiden aloitusta.",
        avatarUrl: ASSETS.portraitOlli,
        bannerUrl: ASSETS.catMuut,
        city: "Espoo",
        languages: ["suomi"],
        experienceYears: 12,
        categories: ["muut"],
        rating: 4.9,
        reviewCount: 58,
        joinedYear: 2022,
        social: { facebook: "vihreapeukalo" },
        certifications: ["Viheralan ammattitutkinto"],
        faq: [{ q: "Tuletko myös kertaluontoisesti?", a: "Kyllä, teen myös kertaluonteisia töitä – esimerkiksi pensasaidan vuosileikkauksen." }],
        portfolioImages: [ASSETS.catMuut],
      },
    ],
    services: [
      {
        id: "s-kylpyhuone",
        providerId: "p-mikko",
        title: "Kylpyhuoneremontti avaimet käteen",
        description:
          "Toteutamme kylpyhuoneremontit avaimet käteen -periaatteella: purku, vesieristys, laatoitus, kalusteet ja sähkötyöt. Saat yhden selkeän hinnan, aikataulun ja projektista vastaavan yhteyshenkilön.\n\nHinta sisältää suunnittelun, materiaalien noudot, työt ja loppusiivouksen. Keskimääräinen remontti valmistuu 3–4 viikossa.",
        category: "koti",
        delivery: "paikan_paalla",
        pricing: "paketti",
        price: 4900,
        paymentModes: ["alusta", "ulkopuolella"],
        city: "Helsinki",
        radiusKm: 30,
        images: [ASSETS.svcBathroom, ASSETS.catKoti],
        tags: ["Remontti", "Vesieristys", "Laatoitus"],
        rating: 4.9,
        reviewCount: 54,
      },
      {
        id: "s-sahkotyot",
        providerId: "p-mikko",
        title: "Sähkötyöt ja valaistuksen asennus",
        description:
          "Kodin sähkötyöt ammattilaisen tekemänä: valaisimien ja pistorasioiden asennukset, sähkökeskukset, liesi- ja kodinkonekytkennät sekä vikojen etsintä.\n\nTuntihinta sisältää matkakulut pääkaupunkiseudulla. Minimiveloitus yksi tunti.",
        category: "koti",
        delivery: "paikan_paalla",
        pricing: "tunti",
        price: 65,
        paymentModes: ["alusta"],
        city: "Helsinki",
        radiusKm: 25,
        images: [ASSETS.catKoti],
        tags: ["Sähkötyöt", "Valaistus", "Asennus"],
        rating: 4.8,
        reviewCount: 41,
      },
      {
        id: "s-verkkosivut",
        providerId: "p-emilia",
        title: "Yrityksen verkkosivut",
        description:
          "Modernit, mobiiliystävälliset ja hakukoneoptimoidut verkkosivut yrityksellesi. Sisältää suunnittelun, 1–5 sivua, yhteystietolomakkeen ja koulutuksen sisällön päivittämiseen.\n\nToteutus valmiilla, turvallisella alustalla – sinä omistat sivut ja sisällöt.",
        category: "digi",
        delivery: "etana",
        pricing: "paketti",
        price: 1490,
        paymentModes: ["alusta"],
        images: [ASSETS.svcWebdesign],
        tags: ["Verkkosivut", "SEO", "WordPress"],
        rating: 5.0,
        reviewCount: 28,
      },
      {
        id: "s-brandi",
        providerId: "p-emilia",
        title: "Brändi-ilme ja logo",
        description:
          "Rakennetaan yrityksellesi yhtenäinen brändi-ilme: logo, väripaletti, typografia ja perusmateriaalit (käyntikortti, esityspohja, some-pohjat).\n\nProsessi sisältää 2 suunnittelukierrosta ja kaikki tiedostot käyttöösi.",
        category: "digi",
        delivery: "etana",
        pricing: "paketti",
        price: 890,
        paymentModes: ["alusta", "ulkopuolella"],
        images: [ASSETS.catDigi],
        tags: ["Brändi", "Logo", "Graafinen suunnittelu"],
        rating: 4.9,
        reviewCount: 33,
      },
      {
        id: "s-verkkokauppa",
        providerId: "p-emilia",
        title: "Verkkokaupan perustaminen",
        description:
          "Perustetaan yrityksellesi toimiva verkkokauppa: tuotehallinta, maksuratkaisut, toimituskulut ja raportointi. Hinta määräytyy laajuuden mukaan – pyydä tarjous!",
        category: "digi",
        delivery: "etana",
        pricing: "tarjous",
        price: null,
        paymentModes: ["alusta", "ulkopuolella"],
        images: [ASSETS.catDigi],
        tags: ["Verkkokauppa", "E-commerce"],
        rating: 4.8,
        reviewCount: 17,
      },
      {
        id: "s-hieronta",
        providerId: "p-suvi",
        title: "Urheiluhieronta 60 min",
        description:
          "Syväkudoshieronta urheilijoille ja liikkujille: palautumisen tueksi, lihasjännityksiin ja liikkuvuuden parantamiseen.\n\nHoito tapahtuu vastaanotollani Tampereen keskustassa. Ota mukaan kevyet vaihtovaatteet.",
        category: "hyvinvointi",
        delivery: "paikan_paalla",
        pricing: "tunti",
        price: 75,
        paymentModes: ["alusta"],
        city: "Tampere",
        radiusKm: 15,
        images: [ASSETS.catHyvinvointi],
        tags: ["Hieronta", "Palautuminen"],
        rating: 4.9,
        reviewCount: 67,
      },
      {
        id: "s-jooga",
        providerId: "p-suvi",
        title: "Jooga aloittelijoille – 8 viikon kurssi",
        description:
          "Rauhallinen 8 viikon joogakurssi pienryhmässä (max 8 hlöä). Opit perusasennot, hengitystekniikat ja rakennat oman kotiharjoituksen.\n\nKurssi kokoontuu kerran viikossa 75 minuutin ajan. Maksu sisältää kaikki 8 kertaa.",
        category: "hyvinvointi",
        delivery: "paikan_paalla",
        pricing: "paketti",
        price: 160,
        paymentModes: ["alusta", "ulkopuolella"],
        city: "Tampere",
        radiusKm: 10,
        images: [ASSETS.svcYoga],
        tags: ["Jooga", "Kurssi", "Pienryhmä"],
        rating: 4.8,
        reviewCount: 22,
      },
      {
        id: "s-muutto",
        providerId: "p-juhani",
        title: "Muuttopalvelu pk-seudulla",
        description:
          "Kokonaisvaltainen muuttopalvelu: pakkausmateriaalit, muuttolaatikot, kantoapu ja kuljetus kuorma-autolla. Toimimme pääkaupunkiseudulla ja lähikunnissa.\n\nLähetä varauspyyntö osoitteineen ja tavaramäärineen, niin saat kiinteän tarjouksen vuorokauden sisällä.",
        category: "kuljetus",
        delivery: "paikan_paalla",
        pricing: "tarjous",
        price: null,
        paymentModes: ["ulkopuolella", "alusta"],
        city: "Helsinki",
        radiusKm: 40,
        images: [ASSETS.catKuljetus],
        tags: ["Muutto", "Kuljetus", "Kantoapu"],
        rating: 4.7,
        reviewCount: 89,
      },
      {
        id: "s-huonekalut",
        providerId: "p-juhani",
        title: "Huonekalukuljetus ja kantoapu",
        description:
          "Yksittäisten huonekalujen ja tavaroiden noudot ja kuljetukset pääkaupunkiseudulla. Kantoapu sisältyy hintaan – myös kerrostaloihin.\n\nPalvelu sisältää yhden nouto- ja yhden toimitusosoitteen (enintään 60 km yhteensä).",
        category: "kuljetus",
        delivery: "paikan_paalla",
        pricing: "paketti",
        price: 89,
        paymentModes: ["alusta"],
        city: "Helsinki",
        radiusKm: 40,
        images: [ASSETS.catKuljetus],
        tags: ["Kuljetus", "Kantoapu"],
        rating: 4.8,
        reviewCount: 52,
      },
      {
        id: "s-piano",
        providerId: "p-anna",
        title: "Pianotunnit verkossa",
        description:
          "Yksityiset pianotunnit videoyhteydellä, kaiken tasoisille. Ensimmäisellä tunnilla kartoitamme lähtötasosi ja tavoitteesi, ja rakennan sinulle henkilökohtaisen harjoitusohjelman.\n\nTunnit pidetään videopuhelun kautta – tarvitset vain koskettimiston ja verkkoyhteyden.",
        category: "opetus",
        delivery: "etana",
        pricing: "tunti",
        price: 40,
        paymentModes: ["alusta"],
        images: [ASSETS.svcPiano],
        tags: ["Piano", "Musiikki", "Etätunnit"],
        rating: 5.0,
        reviewCount: 19,
      },
      {
        id: "s-musiikinperusteet",
        providerId: "p-anna",
        title: "Musiikin perusteet lapsille",
        description:
          "Hauska ja kannustava 6 kerran kurssi 7–12-vuotiaille: rytmiikkaa, nuotinlukua ja yhteissoittoa leikin kautta. Ryhmäkoko max 6 lasta.\n\nMaksu sovitaan suoraan kurssin alkaessa – saat laskun sähköpostiisi.",
        category: "opetus",
        delivery: "etana",
        pricing: "paketti",
        price: 120,
        paymentModes: ["ulkopuolella"],
        images: [ASSETS.catOpetus],
        tags: ["Lapset", "Musiikki", "Kurssi"],
        rating: 4.9,
        reviewCount: 12,
      },
      {
        id: "s-somistus",
        providerId: "p-lumo",
        title: "Hää- ja juhlatilaisuuksien somistus",
        description:
          "Suunnittelemme ja toteutamme juhlatilasi somistuksen kokonaisuudessaan: kukat, kattaukset, valaistus ja yksityiskohdat. Hoidamme myös purun tapahtuman jälkeen.\n\nPyydä tarjous – kerro päivämäärä, paikka ja juhlan tyyppi, niin vastaamme vuorokauden sisällä.",
        category: "tapahtumat",
        delivery: "paikan_paalla",
        pricing: "tarjous",
        price: null,
        paymentModes: ["alusta", "ulkopuolella"],
        city: "Turku",
        radiusKm: 60,
        images: [ASSETS.catTapahtumat],
        tags: ["Häät", "Somistus", "Tapahtumat"],
        rating: 4.9,
        reviewCount: 14,
      },
      {
        id: "s-pihatyot",
        providerId: "p-olli",
        title: "Pihatyöt ja pensasaitojen leikkaus",
        description:
          "Pensasaitojen muoto- ja vuosileikkaukset, nurmikon kylvö ja hoito, harvennukset sekä kevät- ja syyssiivoukset. Jätteet vien mennessäni.\n\nTuntihinta sisältää matkat ja työkalut. Käyn mielelläni etukäteen arvioimassa urakan ja annan kiinteän hinnan.",
        category: "muut",
        delivery: "paikan_paalla",
        pricing: "tunti",
        price: 45,
        paymentModes: ["alusta"],
        city: "Espoo",
        radiusKm: 20,
        images: [ASSETS.catMuut],
        tags: ["Pihatyöt", "Pensasaita", "Nurmikko"],
        rating: 4.9,
        reviewCount: 31,
      },
    ],
    orders: [
      {
        id: "o-1",
        serviceId: "s-muutto",
        providerId: "p-juhani",
        customerId: "u-liisa",
        channel: "ulkopuolella",
        status: "sovitaan",
        amount: null,
        notes: "Muutto Vantaalta Helsinkiin, 2h+k, noin 25 laatikkoa. Toivottu ajankohta: perjantai klo 8.",
        createdAt: day(-3, 9),
        threadId: "t-1",
      },
      {
        id: "o-2",
        serviceId: "s-verkkosivut",
        providerId: "p-emilia",
        customerId: "u-liisa",
        channel: "alusta",
        status: "maksettu",
        amount: 1490,
        notes: "Verkkosivut yritykselle NordFit Oy, 5 alasivua.",
        createdAt: day(-12, 14),
        threadId: "t-2",
      },
      {
        id: "o-3",
        serviceId: "s-sahkotyot",
        providerId: "p-mikko",
        customerId: "u-antti",
        channel: "alusta",
        status: "maksettu",
        amount: 130,
        notes: "Valaisimien asennus olohuoneeseen (2 h).",
        createdAt: day(-5, 11),
        threadId: "t-3",
      },
      {
        id: "o-4",
        serviceId: "s-kylpyhuone",
        providerId: "p-mikko",
        customerId: "u-antti",
        channel: "ulkopuolella",
        status: "sovitaan",
        amount: null,
        notes: "Kylpyhuone noin 5 m². Haluaisimme tarjouksen ja ehdotuksen aikataulusta.",
        createdAt: day(-1, 16),
        threadId: "t-4",
      },
    ],
    threads: [
      {
        id: "t-1",
        orderId: "o-1",
        serviceId: "s-muutto",
        participantIds: ["u-liisa", "u-juhani"],
        updatedAt: day(-2, 15),
        readCount: { "u-liisa": 5 },
        messages: [
          { id: "m-11", authorId: "system", text: "Varauspyyntö lähetetty: Muuttopalvelu pk-seudulla. Maksu sovitaan suoraan toimittajan kanssa.", createdAt: day(-3, 9), system: true },
          { id: "m-12", authorId: "u-liisa", text: "Hei! Muutto Vantaalta Helsinkiin, noin 25 laatikkoa ja pari huonekalua. Onnistuisiko ensi perjantaina?", createdAt: day(-3, 9) },
          { id: "m-13", authorId: "u-juhani", text: "Hei Liisa! Perjantai klo 8 sopii hyvin. Hintahaarukka tuolle määrälle on 380–520 € riippuen kerroksista ja hissistä. Sopiiko?", createdAt: day(-3, 13) },
          { id: "m-14", authorId: "u-liisa", text: "Klo 8 sopii erinomaisesti. Molemmissa päissä on hissi. Tehdään niin!", createdAt: day(-2, 10) },
          { id: "m-15", authorId: "u-juhani", text: "Selvä, laitetaan kalenteriin! Lähetän vahvistuksen ja laskun edellisenä päivänä.", createdAt: day(-2, 15) },
        ],
      },
      {
        id: "t-2",
        orderId: "o-2",
        serviceId: "s-verkkosivut",
        participantIds: ["u-liisa", "u-emilia"],
        updatedAt: day(-11, 12),
        readCount: { "u-liisa": 1 },
        messages: [
          { id: "m-21", authorId: "system", text: "Maksu suoritettu alustan kautta – 1 490 €. Kiitos tilauksestasi!", createdAt: day(-12, 14), system: true },
          { id: "m-22", authorId: "u-emilia", text: "Kiitos tilauksesta, Liisa! Aloitamme suunnittelun maanantaina ja lähetän sinulle ensimmäisen luonnoksen torstaina.", createdAt: day(-12, 15) },
          { id: "m-23", authorId: "u-liisa", text: "Hienoa, odotan innolla! Kuvat löytyvät kotisivuiltamme.", createdAt: day(-11, 12) },
        ],
      },
      {
        id: "t-3",
        orderId: "o-3",
        serviceId: "s-sahkotyot",
        participantIds: ["u-antti", "u-mikko"],
        updatedAt: day(-4, 10),
        readCount: { "u-mikko": 3 },
        messages: [
          { id: "m-31", authorId: "system", text: "Maksu suoritettu alustan kautta – 130 €. Kiitos tilauksestasi!", createdAt: day(-5, 11), system: true },
          { id: "m-32", authorId: "u-antti", text: "Hei! Valaisimet on ostettu, olemme kotona torstaina klo 9 alkaen.", createdAt: day(-5, 12) },
          { id: "m-33", authorId: "u-mikko", text: "Hei Antti! Sopii – tulen torstaina klo 9 ja asennukset valmiina noin 11:ksi.", createdAt: day(-4, 10) },
        ],
      },
      {
        id: "t-4",
        orderId: "o-4",
        serviceId: "s-kylpyhuone",
        participantIds: ["u-antti", "u-mikko"],
        updatedAt: day(-1, 17),
        readCount: { "u-mikko": 2 },
        messages: [
          { id: "m-41", authorId: "system", text: "Varauspyyntö lähetetty: Kylpyhuoneremontti avaimet käteen. Maksu sovitaan suoraan toimittajan kanssa.", createdAt: day(-1, 16), system: true },
          { id: "m-42", authorId: "u-antti", text: "Hei! Kylpyhuone on noin 5 neliötä, vuoden 2005 talossa. Haluaisimme tarjouksen ja arvion aikataulusta.", createdAt: day(-1, 16) },
          { id: "m-43", authorId: "u-mikko", text: "Kiitos yhteydenotosta! Kävisin ensi viikolla ilmaisella kartoituskäynnillä – sopiiko keskiviikko klo 10?", createdAt: day(-1, 17) },
        ],
      },
    ],
  };
}
